Repository ngrok/ngrok-docs, pull requests merged in 2025-10, with the labels that each got.

#1609 Use defaultValue property for status_code in redirect.mdx
  traffic-policy/actions/redirect.mdx
Labels: kind/enhancement, docs/infra

#1612 Correct typo for 3.30 agent release
  agent/version-support-policy.mdx
  traffic-policy/concepts/index.mdx
Labels: docs/content

#1613 Remove langswitcher component
  agent-sdks/index.mdx
  getting-started/index.mdx
  universal-gateway/load-balancing-multiple-clouds.mdx
Labels: kind/bug, docs/design

#1614 Make definition wrapper color-mode aware
  definition-wrapper.js
Labels: kind/enhancement, docs/design

#1617 Some post-migration fixes to Universal Gateway examples (plus other YAML fixes)
  docs.json
  traffic-policy/examples/add-authentication.mdx
  traffic-policy/examples/block-unwanted-requests.mdx
  universal-gateway/examples.mdx
  universal-gateway/examples/multiplex.mdx
Labels: kind/bug, docs/content

#1616 Document Agent API /endpoints API + v3 Config Support
  agent/api.mdx
Labels: docs/content, kind/net-new
